[package]
name = "nile-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
figment = { version = "0.10", features = ["toml", "env"] }
anyhow = "1.0.69"
serde = "1.0.152"
serde_json = "1.0.93"
walkdir = "2.3.2"
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo/", branch = "v1.0.0-alpha.2" }
cairo-lang-compiler = { git = "https://github.com/starkware-libs/cairo/", branch = "v1.0.0-alpha.2" }

[dev-dependencies]
assert_cmd = "2.0.8"
