[package]
name = "nile-rs"
version = "0.1.0"
edition = "2021"
include = ["/base"]

[lib]
name = "nile_rs"
path = "src/nile-rs/lib.rs"

[[bin]]
name = "nile-rs"
test = false
doc = false

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
figment = { version = "0.10", features = ["toml", "env", "test"] }
anyhow = "1.0.69"
serde = "1.0.152"
serde_json = "1.0.93"
walkdir = "2.3.2"
cairo-lang-starknet = "1.0.0-alpha.2"
cairo-lang-compiler = "1.0.0-alpha.2"

[dev-dependencies]
assert_cmd = "2.0.8"
